<Project Sdk="Godot.NET.Sdk/4.6.3">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <TargetFrameworks Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFrameworks>
    <RootNamespace>MagusWarrior</RootNamespace>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="tests/**" />
  </ItemGroup>
</Project>
